### ISSUE TITLE
Some documentation? Possible?,,,,

### ISSUE THREAD

**Issue by puresoul** [Phhere/Qemu#2]
Hi,

today I give a try to your project, because I searching for some very light web gui to qemu. Now i got the webpage working, but don't know, how to add user or password of user "phreh100". Can you help me,  please?

Thanks

**Comment by schiederme** [comment]
Hey @puresoul,
I think the repo is currently not maintained.

I will have a look at documentation next week.

Maxi

**Comment by puresoul** [comment]
thanks for reply ;-)

**Comment by schiederme** [comment]
Hey @puresoul if you are interested in such a script, have a look at https://github.com/PenningDevelopment/openVM :-)
